# example/example_bot/Containerfile

# --- STAGE 1: Builder ---
FROM python:3.11-slim as builder
WORKDIR /build

COPY pyproject.toml .
COPY src/ src/
COPY README.md .
COPY LICENSE .

RUN pip install --upgrade pip build
RUN python -m build

# --- STAGE 2: Runner ---
FROM python:3.11-slim
WORKDIR /app

RUN pip install --upgrade pip

COPY --from=builder /build/dist/*.whl .

RUN pip install kondoo-*.whl pyyaml && rm kondoo-*.whl

EXPOSE 5000
CMD ["python", "-m", "kondoo.app"]